knpu_oauth2_client:
  clients:
    google:
      type: google
      client_id: '%env(resolve:OAUTH_GOOGLE_CLIENT_ID)%'
      client_secret: '%env(resolve:OAUTH_GOOGLE_CLIENT_SECRET)%'
      redirect_route: connect_google_check
      redirect_params: { }
      # scope/hosted_domain can be added later if needed

